local STRINGS = GLOBAL.STRINGS

------------------RECIPE STRINGS-----------------
STRINGS.NAMES.STATUEMARBLEBROODLING = "Marble Broodling Statue"
STRINGS.RECIPE_DESC.STATUEMARBLEBROODLING = "A cute little guy."

-------------------ITEM STRINGS----------------
STRINGS.CHARACTERS.GENERIC.DESCRIBE.STATUEMARBLEBROODLING = "Not a bad effort."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.STATUEMARBLEBROODLING = "This can't contain a fiery soul!"
STRINGS.CHARACTERS.WENDY.DESCRIBE.STATUEMARBLEBROODLING = "A creepy figment."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.STATUEMARBLEBROODLING = "This reproduction is not very accurate."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.STATUEMARBLEBROODLING = "At least this one doesn't buzz incessantly."
STRINGS.CHARACTERS.WX78.DESCRIBE.STATUEMARBLEBROODLING = "IT DOES NOT BUZZ"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.STATUEMARBLEBROODLING = "Will the mum be pleased to see this?"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.STATUEMARBLEBROODLING = "No swat fly!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.STATUEMARBLEBROODLING = "Hello friend, you're not moving! Oh."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.STATUEMARBLEBROODLING = "The idolatry of a great enemy!"

